import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  BookOpen,
  ShieldCheck,
  AlertTriangle,
  CreditCard,
  Clock,
  Globe,
  HelpCircle,
  CheckCircle2,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  AlertOctagon
} from 'lucide-react';

export const SafetyTipsPage: React.FC = () => {
  const [openSection, setOpenSection] = useState<number | null>(0);

  const tips = [
    {
      title: '1. Spotting Fake Online Stores & Unrealistic Discounts',
      icon: AlertOctagon,
      badge: 'Red Flag Warning',
      badgeColor: 'text-rose-400 bg-rose-950/60 border-rose-800',
      summary: 'Fraudulent storefronts lure victims with 70%–90% discounts on high-demand electronics and designer goods.',
      content: [
        'Unbelievable Pricing: If a brand-new $1,200 smartphone or luxury bag is advertised for $79, it is almost certainly counterfeit or non-existent.',
        'Recently Registered Domains: Scammers frequently spin up short-lived websites with cheap TLDs (.shop, .xyz, .top, .vip) that disappear within 60 days.',
        'Copied Product Catalogs: Scammers scrape images directly from legitimate merchants, including stock watermark artifacts.',
        'Missing Physical Address: Legitimate e-commerce retailers clearly state their corporate headquarters, country of registration, and phone lines.'
      ]
    },
    {
      title: '2. Dangerous & Irreversible Payment Methods',
      icon: CreditCard,
      badge: 'Financial Defense',
      badgeColor: 'text-amber-400 bg-amber-950/60 border-amber-800',
      summary: 'Never pay via methods that offer zero buyer dispute rights or chargeback mechanisms.',
      content: [
        'Direct Wire Transfers (Zelle, Wire, Venmo for strangers): These are treated as cash transfers with near-zero recovery options.',
        'Gift Cards or Prepaid Vouchers: No legitimate store requires payment via Apple, Steam, or Amazon gift cards.',
        'Cryptocurrency Payments (Bitcoin, USDT): Once sent on the blockchain, cryptocurrency transactions cannot be reversed or frozen.',
        'Safe Standard: Always use standard credit cards or established payment gateways (PayPal Goods & Services, Apple Pay) which feature built-in zero-liability consumer protection.'
      ]
    },
    {
      title: '3. Instagram Fake Stores & WhatsApp Payment Traps (DM Scam)',
      icon: AlertTriangle,
      badge: 'Social Media Alert',
      badgeColor: 'text-pink-400 bg-pink-950/60 border-pink-800',
      summary: 'Fraudulent sellers lure buyers on Instagram, force them to WhatsApp, take advance UPI payments, and block them.',
      content: [
        'Off-Platform WhatsApp Redirection: "DM for Price / Order on WhatsApp wa.me/..." is designed to bypass Instagram buyer protections and scam detection.',
        'Advance UPI & QR Code Extortion: Asking for GPay / PhonePe / Paytm advance payments or ₹300-₹500 "courier booking charges" even for alleged COD orders.',
        'Fake Courier Receipts: Scammers generate bogus DTDC/Delhivery tracking slips within 2 minutes of payment to deceive victims into paying additional "customs/holding fees".',
        'Disabled Comments on Posts: Fake storefronts always disable or filter comments on their Instagram reels to prevent previous victims from posting warnings.',
        'Defense Rule: Never transfer advance money via personal UPI or QR codes to WhatsApp sellers without a verified GST invoice and official domain checkout.'
      ]
    },
    {
      title: '4. Artificial Urgency Tactics & Manipulative Countdown Timers',
      icon: Clock,
      badge: 'Psychological Coercion',
      badgeColor: 'text-orange-400 bg-orange-950/60 border-orange-800',
      summary: 'Scam websites manipulate buyer psychology using false scarcity and pressure timers.',
      content: [
        'Fake Flashing Countdowns: "Sale ends in 04:59 minutes" that simply restarts upon refreshing the web page.',
        'Fabricated Live Activity: Popups claiming "David from Texas just bought this item 2 minutes ago" generated by random client-side scripts.',
        'Emotional Panic: Scammers force quick decisions so buyers bypass security verification.'
      ]
    },
    {
      title: '4. Typosquatting & Deceptive Lookalike Domains',
      icon: Globe,
      badge: 'Domain Impersonation',
      badgeColor: 'text-cyan-400 bg-cyan-950/60 border-cyan-800',
      summary: 'Attackers create domains with subtle letter substitutions or prefixes to mimic authentic brands.',
      content: [
        'Character Substitution: Using "rn" instead of "m" (e.g. "arnazon.com"), or replacing "o" with "0".',
        'Hyphenated Affixes: Adding terms like "-official", "-outlet", "-clearance-sale", or "-store-us".',
        'Misleading TLDs: Mimicking "brand.com" with "brand-deals.top" or "brand-factory.shop".',
        'Always check the address bar carefully before entering passwords or payment card details.'
      ]
    },
    {
      title: '5. Verifying Merchant Credentials & Reviews',
      icon: ShieldCheck,
      badge: 'Verification Checklist',
      badgeColor: 'text-emerald-400 bg-emerald-950/60 border-emerald-800',
      summary: 'How to independently cross-check customer feedback and merchant reputations.',
      content: [
        'Do Not Trust On-Site Testimonials: Fake stores fabricate 5-star reviews with generic stock photos.',
        'Check Independent Consumer Platforms: Search the domain name on external sites (Trustpilot, Better Business Bureau, Reddit).',
        'Search Query Formula: Google `"[domain.com]" + scam` or `"[domain.com]" + review` to discover recent consumer complaints.',
        'Test Customer Support: Email the listed support address or call their phone before placing large orders.'
      ]
    },
    {
      title: '6. Emergency Steps: What to Do If You Have Been Scammed',
      icon: AlertTriangle,
      badge: 'Immediate Action Plan',
      badgeColor: 'text-rose-400 bg-rose-950/60 border-rose-800',
      summary: 'Immediate critical steps to limit financial loss and initiate chargeback recovery.',
      content: [
        '1. Contact Your Card Issuer Immediately: Request an immediate freeze or cancellation of the card and file a formal fraud dispute/chargeback.',
        '2. Change Compromised Passwords: If you used the same password on the scam site as your email or banking, change them immediately and enable 2FA.',
        '3. File a Report with SafeCart: Submit the domain on SafeCart to alert thousands of other online shoppers.',
        '4. Report to National Cybercrime Authorities: File a report with the FBI Internet Crime Complaint Center (IC3.gov), Federal Trade Commission (ReportFraud.ftc.gov), or your local police cyber cell.'
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-10">
        {/* Header */}
        <div className="text-center space-y-3">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-blue-950/80 border border-blue-500/30 text-blue-400 text-xs font-black uppercase tracking-wider font-mono">
            <BookOpen className="w-3.5 h-3.5" />
            <span>Cybersecurity Knowledge Base</span>
          </div>
          <h1 className="text-4xl sm:text-5xl font-black text-white uppercase tracking-tight">
            E-Commerce Safety Guide
          </h1>
          <p className="text-sm text-slate-400 max-w-2xl mx-auto font-medium">
            Essential tactical indicators to detect scam stores, avoid untraceable payment traps, and protect your identity.
          </p>
        </div>

        {/* Quick Summary Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 space-y-2">
            <div className="text-red-400 font-black uppercase tracking-wider text-xs flex items-center gap-2 font-mono">
              <AlertOctagon className="w-4 h-4" />
              <span>Too Cheap to Be True</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-medium">
              Discounts over 70% on luxury or tech items are the #1 hallmark of scam websites.
            </p>
          </div>

          <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 space-y-2">
            <div className="text-amber-400 font-black uppercase tracking-wider text-xs flex items-center gap-2 font-mono">
              <CreditCard className="w-4 h-4" />
              <span>Unprotected Payments</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-medium">
              Never pay via Zelle, Wire, Crypto, or Gift Cards for physical e-commerce purchases.
            </p>
          </div>

          <div className="p-6 rounded-3xl bg-slate-900 border border-slate-800 space-y-2">
            <div className="text-blue-400 font-black uppercase tracking-wider text-xs flex items-center gap-2 font-mono">
              <Globe className="w-4 h-4" />
              <span>Verify Domain First</span>
            </div>
            <p className="text-xs text-slate-300 leading-relaxed font-medium">
              Inspect domain spelling and run a scan on SafeCart before entering payment credentials.
            </p>
          </div>
        </div>

        {/* Accordion List */}
        <div className="space-y-4">
          {tips.map((tip, idx) => {
            const Icon = tip.icon;
            const isOpen = openSection === idx;
            return (
              <div
                key={idx}
                className="rounded-3xl bg-slate-900 border border-slate-800 overflow-hidden transition"
              >
                <button
                  onClick={() => setOpenSection(isOpen ? null : idx)}
                  className="w-full p-6 text-left flex items-start justify-between gap-4 hover:bg-slate-850 transition cursor-pointer"
                >
                  <div className="flex items-start gap-4">
                    <div className="p-3 rounded-2xl bg-slate-950 border border-slate-800 text-blue-400 shrink-0 mt-0.5">
                      <Icon className="w-6 h-6" />
                    </div>
                    <div>
                      <div className="flex items-center gap-2 mb-1.5">
                        <span className={`text-[10px] font-black px-2.5 py-0.5 rounded-full border uppercase font-mono ${tip.badgeColor}`}>
                          {tip.badge}
                        </span>
                      </div>
                      <h3 className="font-black text-base sm:text-lg text-white uppercase tracking-tight">{tip.title}</h3>
                      <p className="text-xs text-slate-400 mt-1 font-medium">{tip.summary}</p>
                    </div>
                  </div>

                  <div className="p-1 rounded-xl text-slate-400 shrink-0">
                    {isOpen ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                  </div>
                </button>

                {isOpen && (
                  <div className="px-6 pb-6 pt-2 border-t border-slate-800 space-y-3 animate-in fade-in">
                    <div className="space-y-2 text-xs text-slate-300">
                      {tip.content.map((item, itemIdx) => (
                        <div key={itemIdx} className="flex items-start gap-3 p-3.5 rounded-2xl bg-slate-950 border border-slate-800">
                          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                          <span className="leading-relaxed font-medium">{item}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>

        {/* Emergency Authority Help Box */}
        <div className="p-8 rounded-3xl bg-slate-900 border-2 border-red-500/40 space-y-4 shadow-xl">
          <div className="flex items-center gap-3 text-red-400 font-black uppercase tracking-wider text-sm font-mono">
            <AlertTriangle className="w-5 h-5 text-red-500" />
            <span>Official Cybercrime Reporting Portals</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-medium">
            If you have suffered financial loss from an online shopping fraud, file a formal complaint with authorized law enforcement cyber agencies:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 text-xs">
            <a
              href="https://www.ic3.gov"
              target="_blank"
              rel="noreferrer"
              className="p-4 rounded-2xl bg-slate-950 border border-slate-800 hover:border-blue-500 text-slate-200 flex items-center justify-between transition group"
            >
              <div>
                <div className="font-black uppercase tracking-wider group-hover:text-blue-400 text-[11px]">FBI IC3 (USA)</div>
                <div className="text-[10px] text-slate-500 font-mono">Internet Crime Center</div>
              </div>
              <ExternalLink className="w-4 h-4 text-slate-500" />
            </a>

            <a
              href="https://reportfraud.ftc.gov"
              target="_blank"
              rel="noreferrer"
              className="p-4 rounded-2xl bg-slate-950 border border-slate-800 hover:border-blue-500 text-slate-200 flex items-center justify-between transition group"
            >
              <div>
                <div className="font-black uppercase tracking-wider group-hover:text-blue-400 text-[11px]">FTC ReportFraud</div>
                <div className="text-[10px] text-slate-500 font-mono">Consumer Protection</div>
              </div>
              <ExternalLink className="w-4 h-4 text-slate-500" />
            </a>

            <a
              href="https://www.actionfraud.police.uk"
              target="_blank"
              rel="noreferrer"
              className="p-4 rounded-2xl bg-slate-950 border border-slate-800 hover:border-blue-500 text-slate-200 flex items-center justify-between transition group"
            >
              <div>
                <div className="font-black uppercase tracking-wider group-hover:text-blue-400 text-[11px]">Action Fraud (UK)</div>
                <div className="text-[10px] text-slate-500 font-mono">National Fraud Bureau</div>
              </div>
              <ExternalLink className="w-4 h-4 text-slate-500" />
            </a>
          </div>
        </div>

        {/* Scan CTA */}
        <div className="p-8 sm:p-10 rounded-3xl bg-slate-900 border border-slate-800 text-center space-y-4 shadow-xl">
          <h3 className="text-xl sm:text-2xl font-black text-white uppercase tracking-tight">Have a store you want to verify?</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto font-medium">
            Scan the URL with our automated heuristics engine to see its risk breakdown in seconds.
          </p>
          <div>
            <Link
              to="/scanner"
              className="px-8 py-4 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-black uppercase tracking-wider text-xs inline-block shadow-lg shadow-blue-600/30 transition cursor-pointer"
            >
              Go to Website Scanner
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
